"""Shared numerical building blocks for residual-carrier experiments."""

from .nvfp4_reference import (
    E2M1_MAX,
    E2M1_POSITIVE_VALUES,
    LocalScaleMode,
    NVFP4_GLOBAL_DENOMINATOR,
    NVFP4_GROUP_SIZE,
    NVFP4Result,
    UE4M3_MAX,
    UE4M3_MIN_SUBNORMAL,
    compute_global_scale,
    decode_e2m1,
    decode_ue4m3,
    e2m1_codebook,
    encode_e2m1,
    encode_ue4m3,
    nvfp4_quantize,
    quantize_e2m1,
    quantize_nvfp4,
    quantize_ue4m3,
    ue4m3_codebook,
)

__all__ = [
    "E2M1_MAX",
    "E2M1_POSITIVE_VALUES",
    "LocalScaleMode",
    "NVFP4_GLOBAL_DENOMINATOR",
    "NVFP4_GROUP_SIZE",
    "NVFP4Result",
    "UE4M3_MAX",
    "UE4M3_MIN_SUBNORMAL",
    "compute_global_scale",
    "decode_e2m1",
    "decode_ue4m3",
    "e2m1_codebook",
    "encode_e2m1",
    "encode_ue4m3",
    "nvfp4_quantize",
    "quantize_e2m1",
    "quantize_nvfp4",
    "quantize_ue4m3",
    "ue4m3_codebook",
]
